[project]
name = "odoo-addons-oca-storage"
version = "18.0.20241028.0"
dependencies = [
    "odoo-addon-fs_storage==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
